### PR TITLE
fix RT #113081 failure with Test2 based Test::Builder

### PR DESCRIPTION
**Pull request by abraxxa**
requires Test::Simple 1.001005

### CODE REVIEW

**Comment by osfameron** [comment]
Hi @abraxxa, I've invited you as a collaborator, so you can merge the PR, many thanks!

Of course the repo is still badly named as `test-dbic-calls`.  Let me know if you would you like me to rename the repo, or to transfer it to you as well?

**Comment by abraxxa** [comment]
Thanks!
I'd say rename the repo and I'll update the metadata before the next release.

**Comment by osfameron** [comment]
done!

**Comment by abraxxa** [comment]
Just realized that there is no Makefile.pl, Build.pl or dist.ini, how did you generate the tarball in the past?

**Comment by abraxxa** [comment]
And that you already had a branch with both the Makefile.PL as well as a fix almost identical to mine.

**Comment by osfameron** [comment]
Ah, so you've merged that other branch and then your own commit became a no-op?
Sorry, I'd rather left the whole packaging thing slide of late, so thanks again so much for picking it up!
Feel free to move to a different build system if that will make things easier for you.

**Pull request merged**
